name: E2E Test
on: [push, pull_request]

jobs:
  e2e-test:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["8.x", "10.x", "12.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-ci-cypress-${{ hashFiles('package-lock.json') }}
        id: deps-cache

      - name: Install dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Prepare Cypress
        run: npm run cy:verify

      - name: Start MongoDB and NodeGoat
        run: |
          docker run -d -p 27017:27017 mongo:4.0
          until nc -z -w 2 localhost 27017; do sleep 2; done
          NODE_ENV=test npm start -- --silent &

      - name: Run Cypress test suite
        run: npm run test:ci
