name: E2E Test (Docker 2)
on: [push, pull_request]

jobs:
  e2e-test:
    name: Docker + Node.js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["12.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use cache (dependencies)
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-cypress-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          npm run cy:verify
          docker-compose pull

      - name: Use cache (docker layers)
        uses: rcowsill/action-docker-layer-caching@fix/81-release
        continue-on-error: true
        with:
          concurrency: 1
          key: f81-docker-cache-v7-{hash}
          restore-keys: |
            f81-docker-cache-v7-

      - name: Prepare images
        run: |
          docker images -a
          NODE_ENV=test docker-compose build

      - name: Run Cypress test suite
        run: |
          NODE_ENV=test npm run start-infra --silent &
          npm run test:ci
