name: E2E Test
on: [push, pull_request]

jobs:
  e2e-test:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["8.x", "10.x", "12.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci
          npm run cy:verify

      - name: Start MongoDB and NodeGoat
        run: |
          docker run -d -p 27017:27017 mongo:4.0
          timeout 60s bash -c 'until nc -z -w 2 localhost 27017 && echo MongoDB ready; do sleep 2; done'

      - name: Run Cypress test suite
        run: |
          NODE_ENV=test npm start -- --silent &
          npm run test:ci
