name: E2E Test
on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["12.x"]

    steps:
      - name: Checkout ${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }} @ ${{ GITHUB_REF }}
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-cypress-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          npm run cy:verify

      - name: Start MongoDB
        run: |
          docker run -d -p 27017:27017 mongo:4.0
          docker ps -a

      - name: Test E2E
        run: |
          NODE_ENV=test npm start -- --silent &
          npm run test:ci
