name: E2E Test
on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["10.x", "12.x"]

    services:
      mongo:
        image: mongo:4.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-cypress-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          npm run cy:verify
          which docker || true
          docker version || true
          which docker-compose || true
          docker-compose version || true

      - name: Test E2E
        run: |
          NODE_ENV=test npm start -- --silent &
          npm run test:ci
