name: E2E Test
on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["10.x", "12.x"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-cypress-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          du -d 0 -h ~/.npm || true
          du -d 0 -h ~/.cache || true
          npm ci
          npm run cy:verify
          du -d 0 -h ~/.npm || true
          du -d 0 -h ~/.cache || true
      - name: Start MongoDB
        run: |
          sudo apt-get install -y docker.io
          docker run -d -p 27017:27017 mongo:4.0
          docker ps -a
      - name: Test nodegoat
        run: |
          NODE_ENV=test npm start -- --silent &
          npm run test:ci
      
